server:
  port: 8082
  
#datasource configuration  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms_policy_detail?createDatabaseIfNotExist=true
    username: root
    password: root123123
    driver-class-name: com.mysql.cj.jdbc.Driver
   
  # jpa configuration 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  
  application:
    name: cms-policy-service
   
# dailect spring boot can auto detects, but we can set here also
#eureka:
#  client:
#    enabled: false
    

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
 
  cache:
    type: redis
    redis:
      time-to-live: 60000 # TTL in milliseconds
  redis:
    host: localhost
    port: 6379
    password: # leave empty if not set

  